name : nom_custom_workflow

on:
  push:
    branches:
      - master

jobs:

  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload files on FTP server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          # Adresse du serveur
          server: ftpinfo.iutmontp.univ-montp2.fr
          # Numéro de port
          port: 22
          # Nom d'utilisateur
          username: ${{ secrets.MY_SECRET_NAME }}
          # Mot de passe
          password: ${{ secrets.MY_SECRET_PASSWORD }}
          # Dossier de destination dans le serveur
          remote_path: public_html/hello_world_site/
          # Si on utilise sftp
          sftp_only: true